### ISSUE TITLE
To dos

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#1]
Here's a very high level overview of what needs to be done
-  [ ] Get @parbhat up to speed on wagtail and cookiecutter
- [x] Give @parbhat access to our private project on bitbucket this  will act a the template for our wagtail projects
- [x] Slack send @parbhat  invite
- [x] Discuss what needs to be changed the project is far from perfect
- [x] Do it.

**Comment by Parbhat** [comment]
hello @chrisdev, you are saying about this cookiecutter https://github.com/torchbox/wagtail-cookiecutter

**Comment by chrisdev** [comment]
@Parbhat yes but as but get we call our main app core see the textel project
We can loose the puppet stuff since we are using Ansible.

**Comment by Parbhat** [comment]
so I have to modify the wagtail cookiecutter to suit our needs

**Comment by chrisdev** [comment]
We use 
- Anisble
- Foundation 5 we have our sass integration 
- We have a bunch of models and template_tags
- We have some example templates

Most of this stuff is already in textelcu so we have to put a generic version of this into the cookie cutter so we can spin up sites more quickly easily modify them.

**Comment by Parbhat** [comment]
I understand what needs to be done

**Comment by chrisdev** [comment]
Ok so now make a small pull request with the basic template.
- settings
   - by default we use Postgresql
- vagrant
- One app called core
- One model called HomePage
- Template - base.html, home_page.html, 400.html, 500.html
- Just the boiler plate for the template_tag

**Comment by Parbhat** [comment]
ok @chrisdev

**Comment by Parbhat** [comment]
@chrisdev  django does not allow to create app with name core 

CommandError: 'core' conflicts with the name of an existing Python module and cannot be used as an app name. Please try another name.

**Comment by chrisdev** [comment]
Apologies @Parbhat the internet was out at the Conference Centre so I could not review your pull request till now.

**Comment by Parbhat** [comment]
@chrisdev  I was also late in sending pull request
