### ISSUE TITLE
Missing migration for home paged

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#11]
Most likely forgot to add to github repo

![screenshot 2015-04-20 00 25 44](https://cloud.githubusercontent.com/assets/701689/7223688/f9cfbf92-e6f3-11e4-8ad1-fa54f279e1b9.png)
After I ran `makemigrations`
![screenshot 2015-04-20 00 30 45](https://cloud.githubusercontent.com/assets/701689/7223705/85f08272-e6f4-11e4-8b59-9c00ba2872e1.png)

**Comment by Parbhat** [comment]
@chrisdev  actually I tested the project after deleting and creating the database again
