### ISSUE TITLE
StreamField Complete page to showcase all block types

### ISSUE THREAD

**Issue by Parbhat** [chrisdev/wagtail-cookiecutter-foundation#133]
StreamField provides an editing model for freeform content such as blog posts and news stories, allowing diverse content types such as text, images, headings, video and more specialised types such as maps and charts to be mixed in any order.

**Comment by chrisdev** [comment]
Good idea!

**Comment by chrisdev** [comment]
There is a template `/pages/templates/pages/streamfield_complete_page.html` but we need to actually try it out on a "real" site

**Comment by chrisdev** [comment]
Close for now
