### ISSUE TITLE
TemplateSyntaxError when sticking to defaults

### ISSUE THREAD

**Issue by hackebrot** [chrisdev/wagtail-cookiecutter-foundation#156]
Hi there,

I am writing with regards to https://github.com/audreyr/cookiecutter/pull/476. Unfortunately I am getting an error when I try to create a new project with **cookiecutter** on master when I stick to the defaults.

Mac OS X, Python 2.7.10

```python
...
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
  File "./pages/static/js/modernizr.js", line 457
    injectElementWithStyles(['@media (',prefixes.join('touch-enabled),('),mod,')','{#modernizr{top:9px;position:absolute}}'].join(''), function( node ) {
```

**Comment by chrisdev** [comment]
Thanks @hackebrot we're adding some tests and CI with travis to prevent this from happening in the future

**Comment by hackebrot** [comment]
Cool! Happy to hear that :smiley_cat:
