### ISSUE TITLE
Making feeds app more pluggable

### ISSUE THREAD

**Issue by Parbhat** [chrisdev/wagtail-cookiecutter-foundation#182]

**Comment by chrisdev** [comment]
Some of The Stuff that we need to able to tweak to make 
- [ ] title
- [ ] link
- [ ] description
- [ ] author_email
- [ ] author_link
- [ ] Page model e.g BlogPage
- [ ] Field - intro, body etc.

Initially we could add this to the settings. But soon someone will ask for multiple RSS/Atom Feeds.
Maybe a page model that will render XML RSS? Version 0.2.0 perhaps?
