### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by Parbhat** [chrisdev/wagtail-cookiecutter-foundation#22]

**Comment by Parbhat** [comment]
@chrisdev  Wagtail 0.8.6 installs django-taggit==0.12.3 which is outdated and caused problem with django 1.8 
https://requires.io/github/torchbox/wagtail/requirements/?branch=master

The same problem is also with other packages like https://github.com/treyhunner/django-simple-history/issues/156

The problem resolved a

**Comment by chrisdev** [comment]
Hmm suspected as much what about i'm also seeing that the wagtail master is still Django 1.7 we may have to put this on hold until they start supporting Django 1.7

**Comment by Parbhat** [comment]
@chrisdev yes we have to wait

**Comment by chrisdev** [comment]
Have similar issue with django-pandas https://github.com/chrisdev/django-pandas/issues/45.
You want to do some research and tell me what we have to fix?
Or do you prefer to hack on one thing at a time?

**Comment by Parbhat** [comment]
@chrisdev  yes I will do some research work to resolve the issue

**Comment by chrisdev** [comment]
Great so at last you get to work on djano-pandas :smile:

**Comment by Parbhat** [comment]
yes actually I was waiting for it

**Comment by chrisdev** [comment]
At least for now until the new version of Wagtail is out
