### ISSUE TITLE
Support for Foundation for Site V6

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#223]
We already have a version tagged for  Foundation 5 so there is no reason to worry about backwards compatibility.
So Ok here is the change log https://github.com/zurb/foundation-sites/releases/
The big component that is  missing is the clearing lightbox.
We should also support the flexgrid as a default but I'm not sure.

**Comment by Parbhat** [comment]
@chrisdev Brandon Arnold said in the Forum "Upgrade depends on the amount of JS a project is using". Also upgrade docs for V6 will also be out in next year http://foundation.zurb.com/forum/posts/36152-foundation-6-upgrade-docs

**Comment by chrisdev** [comment]
We'll do another blog post next week on this @ilendl2 could you post the conversion guide in out the slack channel

**Comment by chrisdev** [comment]
Closing for now!
