### ISSUE TITLE
Error: media query expression must begin with '('

### ISSUE THREAD

**Issue by cliff85** [chrisdev/wagtail-cookiecutter-foundation#248]
After working through 'Getting Started' and 'Up and Running for Development' I am receiving this error when viewing localhost:8000 after 'make all'
_Error: media query expression must begin with '('
        on line 139 of pages/static/libs/foundation-sites/scss/util/_breakpoint.scss_

139 of  pages/static/libs/foundation-sites/scss/util/_breakpoint.scss
`    @media screen and #{$str} {
`

**Comment by Parbhat** [comment]
@cliff85 thanks for reporting the issue. The reason for the error is the latest release of [libsass](https://github.com/dahlia/libsass-python/releases) (0.10.1). So, meanwhile it is corrected we can use the previous version (0.10.0). The error can be corrected with

    pip install libsass==0.10.0
