### ISSUE TITLE
django_medusa update

### ISSUE THREAD

**Issue by obswork** [chrisdev/wagtail-cookiecutter-foundation#258]
The included make static_site command is slightly broken by the usage of the deprecated django.utils.importlib by django-medusa. Updating django_medusa/renderers/__init__.py to use the standard importlib will fix the issue (as documented in this pr: https://github.com/mtigas/django-medusa/pull/26/files). 

The package seems like it's no longer being maintained (but otherwise works quite well) so perhaps include notes in your documentation concerning this?

**Comment by chrisdev** [comment]
@Parbhat @obswork can this be closed?

**Comment by Parbhat** [comment]
@chris django-medusa is not maintained. We can use the alternatives suggested by the author.

**Comment by chrisdev** [comment]
Ok so we'll recommend the fork https://github.com/alsoicode/django-medusa
Add this to our requirements?

**Comment by Parbhat** [comment]
Yes
