### ISSUE TITLE
Streamline Requirements

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#269]
We need to look at the requirements to make sure we've pinned the correct versions numbers and remove any redundancies.
Try to increase easy of maintenance by moving away from pinning an absolute version # and use conditionals instead

**Comment by chrisdev** [comment]
For example the production version of  Fabric==1.11.1
But do we need to install Fabric on the production or staging? Should it only be on dev machines?

**Comment by purplediane** [comment]
I'm looking at this one.

**Comment by purplediane** [comment]
For this one we are just removing Fabric, as other changes are more complicated, and on a case-by-case basis.

**Comment by chrisdev** [comment]
@purplediane you are correct we need to use something like requires.io. I've set it up and I need to put the badge in the README
