### ISSUE TITLE
DigitalOcean ansible playbook is broken

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#271]
We definitely need to avoiding reinventing the wheel and use the ansible-galaxy (if possible)

**Comment by chrisdev** [comment]
It never worked!

**Comment by chrisdev** [comment]
think we'll remove this as more and more deployment options are popping up like the Aldryn Cloud

**Comment by ilendl2** [comment]
can be closed
