### ISSUE TITLE
Come up with a better name than home for the core app

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#3]
The core app is where all/most of the Page Models live.
In our concrete implementation we call our app core!
@Parbhat has found that the start_app does not like the name `core`
My suggestions is `pages`

**Comment by Parbhat** [comment]
@chrisdev  pages name will be great

**Comment by Parbhat** [comment]
@chrisdev app name can be **core** now, sending the pull request :)

**Comment by chrisdev** [comment]
Ok we are going with pages. This is what they used in pythondotorg https://github.com/python/pythondotorg/blob/master/pages/
We will need the following modules
- blog
- events
- people

**Comment by chrisdev** [comment]
closing this in favour of #23
