### ISSUE TITLE
Change repo_name to project_slug

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#345]
Here's my thinking

- I agree with @pydanny that this is less confusing to people. 

- Also, since cookiecutter-django is the most popular of these cookiecutters then it may make it easier for people to understand, adopt our cookiecutter if we follow the conventions adopted by cookiecutter-django? 

What do you think @Parbhat

**Comment by Parbhat** [comment]
:+1:
