### ISSUE TITLE
Robots and humans

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#36]
Need to add default robots.txt and humans.txt

**Comment by Parbhat** [comment]
@chrisdev I am adding it

**Comment by chrisdev** [comment]
Its ok i've done the commit on master. This is why I need to start using feature branches!!
I will push to master and you can make the changes based on your stuff

**Comment by Parbhat** [comment]
@chrisdev Great

**Comment by Parbhat** [comment]
@chrisdev I think we also have to change urls.py for adding robots.txt and humans.txt completely

http://fredericiana.com/2010/06/09/three-ways-to-add-a-robots-txt-to-your-django-project/
