### ISSUE TITLE
Add image minimisation task to the clean up playbook

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#369]
We already have `make compress_images` so all we need to do is install grunt and dependencies and setup a cron job for the task to run twice a day

**Comment by chrisdev** [comment]
@Parbhat I seem to recall a PR where you addressed this? Can we close now?

**Comment by Parbhat** [comment]
@chrisdev for this we created a `make` command `make node_modules`. Ansible task needs to be created.

**Comment by chrisdev** [comment]
We also have the ability to set/and change the image quality at the global level

`WAGTAILIMAGES_JPEG_QUALITY = 40`

The default is 85
