### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by tkovalsky** [chrisdev/wagtail-cookiecutter-foundation#375]
Got the CMS running locally, but now want to move to a production server on Digital Ocean, but received these errors:

any thoughts?

TASK [Update the source via git] ***********************************************
fatal: [104.131.121.162]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_snWjsk/ansible_module_command.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_snWjsk/ansible_module_command.py\", line 186, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/usr/local/sites/trec'\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by chrisdev** [comment]
Thanks @tkovalsky for giving deployment a try! 
We've realised that Digital Ocean Ubuntu 16.04 boxes don't have the python dependencies required to  run Ansible by default. To deal with this, we have a pre task playbook which uses Ansible's raw (ssh) mode. 

So use 
`make pre_task`
Or 
`ansible-playbook -i ansible/production ansible/pre_task.yml`

 to run this play.  Then run:

`make deploy_user` 

`make provision`
