### ISSUE TITLE
extended feed giving internal server error

### ISSUE THREAD

**Issue by ilendl2** [chrisdev/wagtail-cookiecutter-foundation#379]
extended feed giving internal server error

**Comment by Parbhat** [comment]
@ilendl2 Not able to produce the same error. Extended feed is working fine.

**Comment by ilendl2** [comment]
@Parbhat check out the erroe here

http://birdsongtt.chrisdev.com/blog/feed/extended

**Comment by Parbhat** [comment]
@ilendl2 from error its seems  that the image element doesn't have a `"src"` attribute. We need to handle this in django-wagtail-feeds.
