### ISSUE TITLE
not run： manager load_init_data

### ISSUE THREAD

**Issue by fangaofeng** [chrisdev/wagtail-cookiecutter-foundation#384]
not load init data.

**Comment by chrisdev** [comment]
@fangaofeng try `make initial_data`
Our default pages have gotten pretty complex and tend to break migrations so we're loading the initial data from an SQL dump of the default database for now.

**Comment by fangaofeng** [comment]
Thany you answer. Because i use windows , not make. i read makefile  and when i execute sql by navicat.exe UI   is failed.  but psql shell \i is ok.   now it is run. 
,

**Comment by chrisdev** [comment]
👍 @fangaofeng
