### ISSUE TITLE
Add foundation sass to the home page template

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#4]
- [x] Add foundation SASS
- [x] Javascript dependencies.
- [x] Templates 
     - base.html
     - 400.html
     - 500.html
- [x] The site design should be for a business/marketing
       - [x]  navbar
       - [x]  Hero unit 
       - [x] Welcome content section as a centred box
       - [x] Three content sections
       - [x] Footer with sitemap

**Comment by chrisdev** [comment]
@Parbhat at this stage we not adding any PageModels beyond the HomePage.
Lets concentrate on getting the SASS integration right.
For example in the Textel project I got rid of bower_components sub folder and the bower files.
This means that bower_update no longer works.

**Comment by chrisdev** [comment]
@parbhat
sed -e '1s/^/{% raw %}/' -e '$s/$/{% endraw %}/' form.html

**Comment by Parbhat** [comment]
@chrisdev I have to replace form.html with modernize or ?

**Comment by chrisdev** [comment]
@Parbhat now  good base to we can start making refinements
