### ISSUE TITLE
RSS and Atom Feeds

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#44]
We need to support images so we need to use Rss201rev2Feed

heres a blogpost that can help http://www.mechanicalgirl.com/post/customizing-django-rss-feed/

**Comment by Parbhat** [comment]
@chrisdev In feeds.py in line 65, the image object name is being returned. How to get url of feed_image so url can be returned.

**Comment by chrisdev** [comment]
Ok @Parbhat this seems to work
````
    from wagtail.wagtailimages.models import Filter
    feed_image = my_page.feed_image
    filter,_ = Filter.objects.get_or_create(spec='width-1200')
    img = feed_image.get_rendition(filter)
    print img.url   
 ````

**Comment by Parbhat** [comment]
@chrisdev thanks it worked :)
