### ISSUE TITLE
Top Menu to Offcanvas : wrong tag given in documents. 

### ISSUE THREAD

**Issue by contactr2m** [chrisdev/wagtail-cookiecutter-foundation#445]
http://wagtail-cookiecutter-foundation.readthedocs.io/en/latest/usage/template_tags.html#top-menu-to-offcanvas

it should  be offcanvas_top_menu instead of off_canvas_top_menu. else tag not registered error is raised.

**Comment by chrisdev** [comment]
@ilendl2 @Parbhat have you guys addressed this in any of your recent PR's

**Comment by ilendl2** [comment]
Yes I have
