### ISSUE TITLE
Demo site is 502ing

### ISSUE THREAD

**Issue by ndanielsen** [chrisdev/wagtail-cookiecutter-foundation#483]
https://wagtail.chrisdev.com/
<img width="995" alt="screen shot 2016-12-07 at 9 28 02 am" src="https://cloud.githubusercontent.com/assets/2944777/20971477/8eb0ecca-bc5f-11e6-9c47-b09bea4062c0.png">

**Comment by chrisdev** [comment]
Thanks @ndanielsen. I've restarted the supervisor so the site is up and running now. 
I'm this one is slightly dated. I'm going to deploy the demo based on the latest stuff later on today.

**Comment by ilendl2** [comment]
This issue can be closed. Site is up an running.
