### ISSUE TITLE
Fail on Django Migrations

### ISSUE THREAD

**Issue by ilendl2** [chrisdev/wagtail-cookiecutter-foundation#511]
fatal: [wagtail.chrisdev.com]: FAILED! => {"changed": true, "cmd": ". /home/django/virtualenvs//wagtail_project-env/bin/activate && python manage.py migrate --noinput --settings=wagtail_project.settings.production", "delta": "0:00:02.506160", "end": "2017-01-05 15:19:21.739243", "failed": true, "rc": 1, "start": "2017-01-05 15:19:19.233083", "stderr": "Traceback (most recent call last):\n  File \"manage.py\", line 21, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 367, in execute_from_command_line\n    utility.execute()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 359, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/core/management/base.py\", line 294, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/core/management/base.py\", line 345, in execute\n    output = self.handle(*args, **options)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 83, in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 20, in __init__\n    self.loader = MigrationLoader(self.connection)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 52, in __init__\n    self.build_graph()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 203, in build_graph\n    self.applied_migrations = recorder.applied_migrations()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 65, in applied_migrations\n    self.ensure_schema()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 52, in ensure_schema\n    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 233, in cursor\n    cursor = self.make_cursor(self._cursor())\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 204, in _cursor\n    self.ensure_connection()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 199, in ensure_connection\n    self.connect()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 199, in ensure_connection\n    self.connect()\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 171, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py\", line 176, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File \"/home/django/virtualenvs/wagtail_project-env/local/lib/python2.7/site-packages/psycopg2/__init__.py\", line 164, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, async=async)\ndjango.db.utils.OperationalError: FATAL:  password authentication failed for user \"django\"\nFATAL:  password authentication failed for user \"django\"", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by chrisdev** [comment]
@ilendl2 the DB user password generated by the  cookiecutter post_gen hook had an "@" character in it. I think this may cause a problem with the connection string as used in `django-environ`.

Maybe we should remove the for the list of random characters used for generating the password?
