### ISSUE TITLE
certificate too old

### ISSUE THREAD

**Issue by EgonFrerich** [chrisdev/wagtail-cookiecutter-foundation#559]
Chris!
The certificate on your demo site has expired.
Greetings,
Egon

**Comment by chrisdev** [comment]
Got the warning email last night but forgot about it :)
Thanks @EgonFrerich!
 Got to see what went wrong  with the certbot renew cronjob.

**Comment by chrisdev** [comment]
I had to do a fore renew!

```
letsencrypt --force-renewal renew
```
