### ISSUE TITLE
Upgrade to Wagtail 1.10 and Django 1.11.1

### ISSUE THREAD

**Issue by Parbhat** [chrisdev/wagtail-cookiecutter-foundation#571]
libraries to check

- [x] Django Wagtail feeds

- [x] Django foundation formtags

**Comment by Parbhat** [comment]
@chrisdev Many packages are not compatible with Django 1.11.1 LTS. So, we may first update wagtail to 1.10 after new release of django-wagtail-feeds [(Pull request)](https://github.com/chrisdev/django-wagtail-feeds/pull/31).

**Comment by chrisdev** [comment]
@Parbhat agree the latest release of Wagtail supports Django 1.11 https://github.com/wagtail/wagtail/releases.
I think we can tweak the defaults a bit for example making the PostgreSQL search engine the default for production.
