### ISSUE TITLE
Issues to Address for upcoming release

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#588]
- [x] Currently we're only testing cookiecutter generation but we also need to run some tests at the generated project level. As a starting point we should implement [these] (http://docs.wagtail.io/en/v1.10.1/advanced_topics/testing.html] for all page types and ensure that they are called by Tox and Travis
- [x] Implement [Parent page / Child page](http://docs.wagtail.io/en/v1.10.1/topics/pages.html#parent-page-subpage-type-rules) type rules. For example, ensure that blog pages can only be added to a blog index page.
- [x] Use Wagtail Bakery for static sites
- [x] Ensure that we support wagtail-pg-search-backend
- [x] StreamField All the Things! - Make more use of SteamField blocks everywhere especially in our Blog/Article Pages.  
- [x] Add Markdown support, ideally as a StreamField Block
- [x] Provide better support for images sharing for external systems such social media, blogs apps and so on, by insuring that the [dynamic image serve view](http://docs.wagtail.io/en/v1.10.1/advanced_topics/images/image_serve_view.html#dynamic-image-serve-view) is configured out of the box.
- [ ] Fix the sentry.io integration
- [x] Support JSON feeds
- [x] Implement [Customer Branding]
(http://docs.wagtail.io/en/v1.10.1/advanced_topics/customisation/admin_templates.html#custom-branding)
- [ ] Our generated wagtail project comes with an Editors guide which is based on the Wagtail editors guide but includes documentation on the stuff we've added. We need to update this!
- [x] Support AMP in blogs
- [x] Upgrade to Foundation 6.4.1

**Comment by chrisdev** [comment]
@Parbhat can we check off JSON feeds?

**Comment by Parbhat** [comment]
Yes. Here is PR https://github.com/chrisdev/wagtail-cookiecutter-foundation/pull/610 But it has merge conflicts. Will resolve it

**Comment by chrisdev** [comment]
I'll close all incompatible and dangerous Pyup bot PRs

**Comment by chrisdev** [comment]
👍

**Comment by ilendl2** [comment]
Implementation of Customer Branding has been completed

**Comment by ilendl2** [comment]
our custom models have been added to the documentation
