### ISSUE TITLE
Speed up Online Compression of SASS etc

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#612]
It's becoming a real pain to develop when django-compressor is in online mode. It's really slow and uses up far to many resources. 

One solution appears to make use of `settings.COMPRESS_CACHEABLE_PRECOMPILERS`  as explained [here](http://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CACHEABLE_PRECOMPILERS). 
There may be other compiler setting that we want to check out and play around with.

@Parbhat  lets set up some experiments and report the finding here.

**Comment by Parbhat** [comment]
@chrisdev I tried `settings.COMPRESS_CACHEABLE_PRECOMPILERS` and looks like it speed ups the page load during development. Sending PR

**Comment by chrisdev** [comment]
@ilendl2 can you test this on one of the sites that was generated for the previous version one this cookiecutter
