### ISSUE TITLE
The attribute 'linktype' may not appear in tag 'a'

### ISSUE THREAD

**Issue by ilendl2** [chrisdev/wagtail-cookiecutter-foundation#651]
@Parbhat @chrisdev When there is an page link from within the site this error comes up when checking amp test.

The attribute 'linktype' may not appear in tag 'a'

![screen shot 2017-09-12 at 12 09 43 pm](https://user-images.githubusercontent.com/1437207/30336504-5b587c1e-97b3-11e7-8ef8-7c49aa38d477.png)

**Comment by Parbhat** [comment]
@ilendl2 Hello, Can you point to the `template` from where the issue arises? Thanks.

**Comment by Parbhat** [comment]
@chrisdev @ilendl2 This [line](https://github.com/chrisdev/wagtail-cookiecutter-foundation/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/blog/models.py#L130) to get `html` will work only for `StreamField`. In case the `body` field is `richtext`, the line will be `expand_db_html(self.body)` using

`from wagtail.wagtailcore.rich_text import expand_db_html`
