### ISSUE TITLE
Doubled requirement if answered yes to use_django_cachalot

### ISSUE THREAD

**Issue by Vicarium** [chrisdev/wagtail-cookiecutter-foundation#676]
Hey,

The line [requirements/base.py Line 18](https://github.com/chrisdev/wagtail-cookiecutter-foundation/blob/974e7c5627a3d71139aa65c9c93c0574dff55b9e/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt#L18) will cause a doubled requirement error. Either that line should be removed along with the option not to include django-cachalot when cookiecutter is run or the line [requirements/base.py line 5](https://github.com/chrisdev/wagtail-cookiecutter-foundation/blob/974e7c5627a3d71139aa65c9c93c0574dff55b9e/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt#L5) should be deleted and line 18's version number increased.

Just thought I should point it out if nobody has noticed, thanks for all your work on this!

**Comment by chrisdev** [comment]
Thanks @Vicarium. I being promising to get back to  django-cachlot integration since our initial efforts resulted in worse performance. What has been your experience with wagtail and django-cachalot
