### ISSUE TITLE
Contact Page returning 500

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#73]
Not sure if this has something to do with the busted fixture?

**Comment by Parbhat** [comment]
@chrisdev the problem is with fixtures, I instead of loading fixtures, I created a new contact page then I works fine. May be we have to create fixtures again

**Comment by chrisdev** [comment]
@Parbhat generate a new fixture using:
````
  ./manage.py dumpdata  --indent=2 --natural-foreign --exclude=contenttypes --exclude=sessions.Session > initial_data.json
```
