### ISSUE TITLE
Support for Bower package manager

### ISSUE THREAD

**Issue by Parbhat** [chrisdev/wagtail-cookiecutter-foundation#79]

**Comment by chrisdev** [comment]
We used the libsass http://foundation.zurb.com/docs/sass.html. I think that we changed the name of directories in to make it simpler. This was a bit of an error. We should use the standard Zurb setup

**Comment by Parbhat** [comment]
@chrisdev I have checked bower is working fine with foundation and our other packages. Bower uses this setup by Zurb https://github.com/zurb/bower-foundation

**Comment by chrisdev** [comment]
Really. so we could do a ``bower update``?

**Comment by Parbhat** [comment]
yes It is working I am about to send the PR

**Comment by chrisdev** [comment]
Great work :+1: not been able to update the version of Foudation was a big hassle with our pinax-theme-foundation

**Comment by Parbhat** [comment]
thanks @chrisdev

**Comment by Parbhat** [comment]
@chrisdev cookiecutter is creating problems with bower generated files, so I think we have to leave it to the user to do

**Comment by chrisdev** [comment]
@Parbhat Well we can explain in the documentation

**Comment by Parbhat** [comment]
@chrisdev ok :)
