### ISSUE TITLE
wagtail latest is not compatible with django latest

### ISSUE THREAD

**Issue by halacsy** [chrisdev/wagtail-cookiecutter-foundation#851]
The latest wagtail is not yet compatible with the freshly released django 2.1 as this [link suggests](https://www.reddit.com/r/django/comments/9ai3xl/wagtail_and_django_21/)

`pip install git+https://github.com/wagtail/wagtail.git@7938e81ab48327a084ac1dced9474c998fd44c2d`

solved the problem

**Comment by chrisdev** [comment]
Thanks @halacsy!
